### ISSUE TITLE
请问这个插件在picgo的command下如何使用，我用的是ubuntu，没法用gui

### ISSUE THREAD

**Issue by lzcxfz** [yuanyxh/picgo-plugin-custom-uploader#1]
作者可以提供一个typora配置的模板给我吗，谢谢啦

**Comment by yuanyxh** [comment]
> 作者可以提供一个typora配置的模板给我吗，谢谢啦

你可以看看 [PicGo-Core#CLI](https://picgo.github.io/PicGo-Core-Doc/zh/guide/commands.html) 部分，应该可以满足你的需求；具体操作如下：
- 全局安装 picgo
- add free-uploader
- 执行 picgo use 命令，选择 free-uploader
- 执行 picgo set uploader，选择并配置

如果你希望使用脚本功能，你需要找到配置文件在指定位置配置 code 字段并填入脚本。

下面是我的配置截图：

![image](https://user-images.githubusercontent.com/72425622/232226760-e7af7f08-8920-499b-bf56-bedac07498de.png)

**Comment by lzcxfz** [comment]
好的 非常感谢！

**Comment by lzcxfz** [comment]
> > 作者可以提供一个typora配置的模板给我吗，谢谢啦
> 
> 你可以看看 [PicGo-Core#CLI](https://picgo.github.io/PicGo-Core-Doc/zh/guide/commands.html) 部分，应该可以满足你的需求；具体操作如下：
> 
> * 全局安装 picgo
> * add free-uploader
> * 执行 picgo use 命令，选择 free-uploader
> * 执行 picgo set uploader，选择并配置
> 
> 如果你希望使用脚本功能，你需要找到配置文件在指定位置配置 code 字段并填入脚本。
> 
> 下面是我的配置截图：
> 
> ![image](https://user-images.githubusercontent.com/72425622/232226760-e7af7f08-8920-499b-bf56-bedac07498de.png)

好的 非常感谢
