### ISSUE TITLE
读取了一个undefined的值

### ISSUE THREAD

**Issue by pillarcoin** [yuanyxh/picgo-plugin-custom-uploader#2]
非常感谢您提供的picgo的插件,它十分符合我的需要,但是好像出了一点小问题.
我自己为cloudinary图床在vercel上新建了一个function call
它只需要在formdata请求中提供两个参数
- file => 文件
- uploadKey =>自定义的key

在我的本地postman测试中,这个function call运行良好,但是当我将参数配到picgo时,picgo插件报错了
插件的配置很简单和明了,我不知道在哪里出错了,能提供一些建议吗,十分感谢.
这是具体的错误信息:[错误信息图](https://res.cloudinary.com/higher/image/upload/v1693655089/blog/2023/09/02/Screenshot_20230902_Oymmhd.png)

请求路径可以尝试调用这个排查https://custom-pic-upload.vercel.app/api/cloudinaryProcess
uploadKey如上图所示

vercel function call的仓库地址在这[仓库地址](https://github.com/liangyi9812/CustomPicUpload)

**Comment by yuanyxh** [comment]
> 非常感谢您提供的picgo的插件,它十分符合我的需要,但是好像出了一点小问题. 我自己为cloudinary图床在vercel上新建了一个function call 它只需要在formdata请求中提供两个参数
> 
> * file => 文件
> * uploadKey =>自定义的key
> 
> 在我的本地postman测试中,这个function call运行良好,但是当我将参数配到picgo时,picgo插件报错了 插件的配置很简单和明了,我不知道在哪里出错了,能提供一些建议吗,十分感谢. 这是具体的错误信息:[错误信息图](https://res.cloudinary.com/higher/image/upload/v1693655089/blog/2023/09/02/Screenshot_20230902_Oymmhd.png)
> 
> 请求路径可以尝试调用这个排查https://custom-pic-upload.vercel.app/api/cloudinaryProcess uploadKey如上图所示
> 
> vercel function call的仓库地址在这[仓库地址](https://github.com/liangyi9812/CustomPicUpload)

这是一个错误，在没有使用高级脚本功能时，现在已经修复了这个问题，你可以更新后再次尝试。
